In [5]:
naame = "Figure"
age = 56
print("%s is %d years old." %(naame, age))

Figure is 56 years old.


In [11]:
sqlist=[x*x for x in range(1, 10)]
sqlist

[1, 4, 9, 16, 25, 36, 49, 64, 81]

In [15]:
cm = [ch.upper() for ch in 'comprehension' if ch not in 'aeiou']
cm

['C', 'M', 'P', 'R', 'H', 'N', 'S', 'N']

In [23]:
import math
integer = input('Type a positive integer: ')
if int(integer) < 0:
    raise RuntimeError("Number must be positive to find Sqrt.")
else: 
    print('The square root is ', math.sqrt(int(integer)))

Type a positive integer: 8
The square root is  2.8284271247461903


In [61]:
def sqroot(n):
    root = n/2
    for k in range(100000):
        root = 1/2*(root + (n/root))
        
    return root 

def sqrootre(n): 
    root = n/2
    if (root*root == n):
        return root
    
    sqrootre(1/2*(root + n/root))
        

In [62]:
sqrootre(5)

RecursionError: maximum recursion depth exceeded in comparison

In [68]:
#CLASSES IN PYTHON
class Fraction: 
    def __init__(self, top, bottom):
        self.num = top
        self.den = bottom
        print(top, bottom, ' , these were passed.')
    
    def __str__(self):
        return str(self.num)+"/"+str(self.den)

In [69]:
Fraction(30, 90)
print(Fraction(30, 89))

30 90  , these were passed.
30 89  , these were passed.
30/89


In [85]:
import time
start = time.time()
end = time.time()
print("start: ",start, " end: ", end, end-start)
print("\n\n")
print(time.process_time())
time.process_time()

start:  1569259592.20737  end:  1569259592.2074182 4.8160552978515625e-05



32.50476


32.504926

In [80]:
help(time.clock)

Help on built-in function clock in module time:

clock(...)
    clock() -> floating point number
    
    Return the CPU time or real time since the start of the process or since
    the first call to clock().  This has as much precision as the system
    records.



In [87]:
#Numpy usage

import numpy as np
a = np.arange(15).reshape(3,5)

In [88]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [91]:
a.shape

(3, 5)

In [92]:
a.ndim

2

In [94]:
a.dtype.name

'int64'

In [95]:
a.itemsize

8

In [96]:
a.size

15

In [97]:
b = np.array([6, 7, 8])

In [98]:
b

array([6, 7, 8])

In [104]:
c = np.array(((3, 4, 5 ), (3, 5, 6)), dtype=complex)

In [105]:
c

array([[3.+0.j, 4.+0.j, 5.+0.j],
       [3.+0.j, 5.+0.j, 6.+0.j]])

In [110]:
d = np.zeros((4,5,4,3))

In [112]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [115]:
np.arange(0, 2, 0.2)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

In [116]:
from numpy import pi

In [118]:
np.linspace(0,2, 10)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [120]:
np.linspace(0,2*pi, 10)

array([0.        , 0.6981317 , 1.3962634 , 2.0943951 , 2.7925268 ,
       3.4906585 , 4.1887902 , 4.88692191, 5.58505361, 6.28318531])

In [123]:
np.zeros_like(np.linspace(0,2, 10))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [124]:
a = np.arange(10)**3

In [125]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [126]:
a[2]

8

In [127]:
a[2:5]

array([ 8, 27, 64])

In [130]:
a[:6:2] = -1000
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729])

In [131]:
for i in a:
    print(i**(1/3.))

nan
1.0
nan
3.0
nan
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


/Users/codenics/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in power
  


In [132]:
def f(x, y):
    return 10*x+y

In [133]:
b = np.fromfunction(f, (5,4), dtype=int)

In [134]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [137]:
b[4, 2]

42

In [139]:
b[0:5, 3]

array([ 3, 13, 23, 33, 43])

In [140]:
b[1:3, :]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [144]:
b[-3, 1]

21

In [150]:
a = np.arange(12)**2
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [148]:
i = np.array([1,1,3,8,5])

In [149]:
a[i]

array([ 1,  1,  9, 64, 25])

In [151]:
j = np.array([[3,4], [9,7]])

In [152]:
a[j]

array([[ 9, 16],
       [81, 49]])

In [153]:
a = np.arange(12).reshape(3,4)

In [154]:
b = a>4

In [155]:
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [156]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [157]:
a[b]=0

In [158]:
a

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])

In [159]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [167]:
a = np.arange(30)
a.shape = 3,-1,2

In [168]:
a.shape

(3, 5, 2)